# Test (always)

name: Test

on:
  workflow_run:
    workflows: [lint]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pytest
        run: pip install pytest
      - name: Test with pytest
        run: pytest -v --doctest-modules
